name: Build and Push Client to Digital Ocean

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

env:
  REGISTRY: registry.digitalocean.com/sisyphus-registry
  IMAGE_NAME: sisyphus-client
  API_URL: https://sisyphus.garnaudov.com/api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set API
        run: echo "REACT_APP_API_URL=${API_URL}" >> client/.env

      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) -f client/Dockerfile client

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Authorize docker to push to DO container registry
        run: doctl registry login --expiry-seconds 900

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)

      - name: Update Kubernetes manifests
        run: |
          git clone https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/gd-arnold/sisyphus-infra.git
          cd sisyphus-infra/kubernetes/sisyphus-client

          sed -i "s|image: registry.digitalocean.com/sisyphus-registry/sisyphus-client:.*|image: registry.digitalocean.com/sisyphus-registry/sisyphus-client:$(echo $GITHUB_SHA | head -c7)|" deployment.yaml

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git add deployment.yaml
          git commit -m "chore: k8s: update siyphus-client image tag to $(echo $GITHUB_SHA | head -c7)"
          git push
