name: Build and Push API to Digital Ocean

on:
  push:
    branches:
      - main
    paths:
      - "client/**"

env:
  REGISTRY: registry.digitalocean.com/sisyphus-registry
  IMAGE_NAME: sisyphus-client
  API_URL: https://sisyphus.garnaudov.com/api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set API
        run: echo "REACT_APP_API_URL=${API_URL}" >> client/.env

      - name: Build image
        run: docker build -t $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7) -f client/Dockerfile client

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}

      - name: Authorize docker to push to DO container registry
        run: doctl registry login --expiry-seconds 900

      - name: Push image
        run: docker push $REGISTRY/$IMAGE_NAME:$(echo $GITHUB_SHA | head -c7)
